[package]
name = "rastronomy"
version = "0.1.1"
authors = ["Gustavo Schwarz gustavo.b.schwarz@gmail.com", "Vincenzo Alberice alberice.vincenzo@gmail.com", "Thales Lopes thales.t.lopes@gmail.com"] # A list of the package authors

homepage = "https://github.com/schwarzam/rastronomy"
license = "Apache-2.0" # The license your package is under

readme = "README.md"

description = "Astronomical package to deal with FITS (compressed also) and WCS, still in development."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.7.0"
ndarray = { version = "0.15.6", features = ["rayon"] }
ndarray-stats = "0.5.1"
memmap = "0.7"
byteorder = "1.4.3"

[build-dependencies]
cc = "1.0.79"