[package]
name = "rastronomy"
version = "0.1.0"
authors = ["Gustavo Schwarz gustavo.b.schwarz@gmail.com", "Vincenzo Alberice alberice.vincenzo@gmail.com", "Thales Lopes thales.t.lopes@gmail.com"] # A list of the package authors

homepage = "https://github.com/schwarzam/rastronomy"
license = "MIT" # The license your package is under

readme = "README.md"

description = "Astronomical package to deal with FITS (compressed also) and WCS, still in development."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
