[package]
name = "rust-astro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4" # For tests
rayon = "1.7.0"
ndarray = { version = "0.15.6", features = ["rayon"] }
ndarray-stats = "0.5.1"
memmap = "0.7"
byteorder = "1.4.3"

[build-dependencies]
cc = "1.0.79"
