[package]
name = "fitstest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fitsio = { version="0.21.2", features=["array"]}
ndarray = "0.15.6"
ndarray-stats = "0.5.1"

[build-dependencies]
cc = "1.0.79"
